var expect = require("chai").expect;
var openBitmapFile = require("../lib/open_bitmap_file.js");
var readFileHeader = require("../lib/read_file_header.js");
var readColorPalette = require("../lib/read_the_color_palette.js");

describe("readColorPalette readPalette()", function(){
  it("should read the color palette table into bitmapObject", function () {
    var bitmapObject = {};
    bitmapObject.paletteSize = 256;
    bitmapObject.palettes = [];

    var bitmapFileName = 'test.bmp';

    var bitmap = openBitmapFile.openFile(bitmapFileName);

    console.log("inside readColorPalette_test.js");
    if (bitmap) {
      console.log("bitmap is not null");
    }
    console.log(bitmapObject);

    var results = readColorPalette.readPalette(bitmap,bitmapObject);

    var testBitmapObject = {
      palettes: [
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 52, green: 32, red: 34, alpha: 0 },
       { blue: 60, green: 40, red: 69, alpha: 0 },
       { blue: 49, green: 57, red: 102, alpha: 0 },
       { blue: 59, green: 86, red: 143, alpha: 0 },
       { blue: 38, green: 113, red: 223, alpha: 0 },
       { blue: 102, green: 160, red: 217, alpha: 0 },
       { blue: 154, green: 195, red: 238, alpha: 0 },
       { blue: 54, green: 242, red: 251, alpha: 0 },
       { blue: 80, green: 229, red: 153, alpha: 0 },
       { blue: 48, green: 190, red: 106, alpha: 0 },
       { blue: 110, green: 148, red: 55, alpha: 0 },
       { blue: 47, green: 105, red: 75, alpha: 0 },
       { blue: 36, green: 75, red: 82, alpha: 0 },
       { blue: 57, green: 60, red: 50, alpha: 0 },
       { blue: 116, green: 63, red: 63, alpha: 0 },
       { blue: 130, green: 96, red: 48, alpha: 0 },
       { blue: 225, green: 110, red: 91, alpha: 0 },
       { blue: 255, green: 155, red: 99, alpha: 0 },
       { blue: 228, green: 205, red: 95, alpha: 0 },
       { blue: 252, green: 219, red: 203, alpha: 0 },
       { blue: 255, green: 255, red: 255, alpha: 0 },
       { blue: 183, green: 173, red: 155, alpha: 0 },
       { blue: 135, green: 126, red: 132, alpha: 0 },
       { blue: 106, green: 106, red: 105, alpha: 0 },
       { blue: 82, green: 86, red: 89, alpha: 0 },
       { blue: 138, green: 66, red: 118, alpha: 0 },
       { blue: 50, green: 50, red: 172, alpha: 0 },
       { blue: 99, green: 87, red: 217, alpha: 0 },
       { blue: 186, green: 123, red: 215, alpha: 0 },
       { blue: 74, green: 151, red: 143, alpha: 0 },
       { blue: 48, green: 111, red: 138, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 },
       { blue: 0, green: 0, red: 0, alpha: 0 }
      ]};

    expect(results.palettes).to.deep.equal(testBitmapObject.palettes);
  });

});
